---
- name: Deploy existing Docker web app
  hosts: myserver
  become: yes

  tasks:
    #- name: Pull existing web app image
     # docker_image:
      #  name: docker/welcome-to-docker
       # source: pull
    - name: Pull existing web app image
      docker_image:
        name: nginxdemos/hello
        source: pull


    - name: Stop old container if exists
      docker_container:
        name: myapp
        state: absent

    - name: Run the web app container
      docker_container:
        name: myapp
        #image: docker/welcome-to-docker
        image: nginxdemos/hello
        state: started
        restart_policy: always
        published_ports:
            - "80:80"
        #ports:
         # - "80:80"
